apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager-webhook-gandi-build-0-4-8
spec:
  template:
    spec:
      containers:
      - image: gcr.io/kaniko-project/executor:latest
        args: 
        - "--dockerfile=/tmp/build/Dockerfile"
        - "--context=dir:///tmp/build"
        - "--destination=ghcr.io/schirrms/cert-manager-webhook-gandi:0.4.8"
        name: cert-manager-webhook-gandi
        resources: {}
        volumeMounts:
        - name: build-tools-volume
          mountPath: /tmp/build
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      volumes:
        - name: build-tools-volume
          hostPath: 
            path: /work/git/cert-manager-webhook-gandi
        - name: kaniko-secret
          secret:
            secretName: ghcrcred
            items:
              - key: .dockerconfigjson
                path: config.json
      restartPolicy: Never
status: {}